version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:2.6.9-node
    steps:
      - checkout
      - ruby/install-deps
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec
      # - ruby/rspec-test

workflows:
  build_and_test_deploy:
    jobs:
      - build_and_test